import { assessFrostRisk, ENGINE_VERSION } from '@/lib/engine'
import { getOwnerId } from '@/lib/session'
import { getStore } from '@/lib/store'
import { fetchAlerts, fetchForecast } from '@/lib/weather'
import { replayChain } from '@/lib/integrity'
import { SITE } from '@/lib/site'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

/**
 * The takeaway artifact: a real downloadable frost brief.
 *
 * Markdown, because a grower pastes it into a group chat or a notes app. It carries the
 * forecast provenance and timestamps, the itemised factor arithmetic, the recommendation with
 * its disclaimer, and the chain head so the brief can be checked later.
 */
export async function GET(request: Request) {
  const url = new URL(request.url)
  const sheetId = url.searchParams.get('sheet')

  let lines: string[] = []
  let filename = 'frostwatch-brief.md'

  try {
    const ownerId = await getOwnerId()
    const store = await getStore()
    const blocks = await store.listBlocks()
    const sheets = sheetId === null ? [] : [await store.getSheet(sheetId, ownerId)].filter((s) => s !== null)

    if (sheets.length === 0) {
      // No sheet selected: brief every block instead of erroring, which is still useful.
      lines = [`# Frostwatch brief`, ``, `Generated ${new Date().toISOString()}`, `Engine ${ENGINE_VERSION}`, ``]
      for (const block of blocks) {
        const forecast = await fetchForecast(block)
        const result = assessFrostRisk({
          points: forecast.points,
          thresholdC: block.thresholdC,
          cropStage: block.cropStage,
        })
        lines.push(...blockSection(block, forecast, result))
      }
    } else {
      for (const sheet of sheets) {
        const block = blocks.find((b) => b.id === sheet.blockId)
        if (block === undefined) continue
        const forecast = await fetchForecast(block)
        const alerts = await fetchAlerts(block.lat, block.lon)
        const result = assessFrostRisk({
          points: forecast.points,
          thresholdC: sheet.thresholdC,
          cropStage: sheet.cropStage,
        })
        const replay = replayChain(await store.eventsFor(sheet.id))
        lines.push(
          `# Frost brief — ${block.label}`,
          ``,
          `- Sheet: \`${sheet.id}\` (status: ${sheet.status})`,
          `- Night of: ${sheet.nightOf}`,
          `- Crop stage: ${sheet.cropStage}, threshold ${sheet.thresholdC}°C`,
          `- Generated: ${new Date().toISOString()}`,
          `- Engine: ${ENGINE_VERSION}`,
          `- Audit chain: ${replay.ok ? 'verified' : `BROKEN at seq ${replay.brokenAtSeq}`}, head \`${replay.headSeal.slice(0, 24)}…\``,
          `- Active NWS alerts: ${alerts.items.length}`,
          ``,
          ...blockSection(block, forecast, result),
        )
        if (sheet.notes.trim() !== '') {
          lines.push(`## Grower notes`, ``, sheet.notes, ``)
        }
      }
      filename = `frost-brief-${sheets[0]!.id}.md`
    }

    lines.push(
      `---`,
      ``,
      `Generated by [${SITE.name}](${SITE.repo}).`,
      `Forecast attribution: Open-Meteo.com (CC BY 4.0). Alerts: NOAA/NWS api.weather.gov.`,
      ``,
      `> Automated guidance from a public forecast, not an agronomic recommendation. Confirm with your own field sensors and local extension advice before acting.`,
      ``,
    )

    return new Response(lines.join('\n'), {
      status: 200,
      headers: {
        'content-type': 'text/markdown; charset=utf-8',
        'content-disposition': `attachment; filename="${filename}"`,
        'cache-control': 'no-store',
      },
    })
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause)
    return new Response(`# Export failed\n\n${message}\n`, {
      status: 500,
      headers: { 'content-type': 'text/markdown; charset=utf-8' },
    })
  }
}

function blockSection(
  block: { label: string; lat: number; lon: number; cropStage: string; thresholdC: number },
  forecast: { status: string; fetchedAt: string; source: string; sourceUrl: string; attribution: string; note?: string },
  result: ReturnType<typeof assessFrostRisk>,
): string[] {
  return [
    `## ${block.label}`,
    ``,
    `- Coordinates: ${block.lat}, ${block.lon}`,
    `- Crop stage: ${block.cropStage}, threshold ${block.thresholdC}°C`,
    `- Forecast: **${forecast.status}** from ${forecast.source}, fetched ${forecast.fetchedAt}`,
    `- Source URL: ${forecast.sourceUrl}`,
    ...(forecast.note === undefined ? [] : [`- Note: ${forecast.note}`]),
    ``,
    `**Risk score ${result.score}/100 (${result.band}) — recommendation: ${result.recommendation}**`,
    ``,
    result.headline,
    ``,
    `| Factor | Weight | Observed | Contribution |`,
    `| --- | --- | --- | --- |`,
    ...result.factors.map(
      (factor) => `| ${factor.label} | ${factor.weight} | ${factor.value} | ${factor.contribution} |`,
    ),
    ``,
    `Minimum temperature ${result.minTempC}°C, ${result.hoursBelow} hour(s) below the effective threshold.`,
    ``,
    ...(result.windows.length === 0
      ? []
      : [
          `Cold windows:`,
          ``,
          ...result.windows.map((window) => `- ${window.from} → ${window.to}, min ${window.minTempC}°C, ${window.hoursBelow} h`),
          ``,
        ]),
    ...result.factors.map((factor) => `- ${factor.label}: ${factor.rationale}`),
    ``,
  ]
}
